version: '3.8'
x-environment-defaults: &environment-defaults
  CELERY_BROKER_URL: "redis://redis:6379/0"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
    environment:
      <<: *environment-defaults

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./backend
    command: celery -A myproject worker --loglevel=info
    volumes:
      - ./backend:/backend
    depends_on:
      - redis
    environment:
      <<: *environment-defaults

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  static_volume: