# Generated by Django 4.2.7 on 2023-12-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='company',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='receiver_staff',
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=40),
        ),
    ]
