# Generated by Django 4.2.7 on 2023-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_alter_warehouseproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=40),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
