# Generated by Django 4.2.7 on 2023-12-20 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0022_alter_warehouseproduct_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='status',
            field=models.CharField(choices=[('sold', 'Sold'), ('available', 'Available')], default='available', max_length=40),
        ),
    ]
