# Generated by Django 4.2.7 on 2024-01-29 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_customer_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='menu_item',
            new_name='item',
        ),
    ]
