# Generated by Django 4.2.7 on 2024-01-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rename_menu_item_orderitem_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='menu_item',
        ),
    ]
