# Generated by Django 4.2.7 on 2024-02-02 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_remove_order_items'),
        ('customer', '0007_remove_orderitem_menu_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
