# Generated by Django 4.2.7 on 2023-12-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_owner',
        ),
    ]
