# Generated by Django 4.2.7 on 2024-01-31 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_company_alter_menuitem_company'),
        ('company', '0009_order_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menuitem'),
        ),
    ]
