# Generated by Django 4.2.7 on 2024-01-31 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_orderitem_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
