# Generated by Django 4.2.7 on 2024-01-24 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_employeeposition_remove_user_is_admin_and_more'),
        ('account', '0004_user_is_customer'),
    ]

    operations = [
    ]
