# Generated by Django 4.2.7 on 2024-01-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_merge_20240124_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.DeleteModel(
            name='CustomerUser',
        ),
    ]
